language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - pip install -U configparser
before_script:
    - wget https://gist.githubusercontent.com/anaganisk/f31adf060b1cecfc7a7b36fbbdce5253/raw/baffb1ff51e09916990e6efc9f8b7bfd5351e7cc/env.ini
script:
    - platformio run
